---
title: "Calculating Individual Scores"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Calculating Individual Scores}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bwsTools)
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r run}
set.seed(1839)
res1 <- diffscoring(vdata, "id", "block", "issue", "value")
res2 <- e_bayescoring(vdata, "id", "block", "issue", "value")
res3 <- eloscoring(vdata, "id", "block", "issue", "value")
res4 <- walkscoring(vdata, "id", "block", "issue", "value")
res5 <- prscoring(vdata, "id", "block", "issue", "value")
```

```{r correl}
res <- list(res1, res2, res3, res4, res5) %>% 
  Reduce(function(x, y) left_join(x, y, by = c("id", "issue")), .)

round(cor(res[, -1:-2]), 2)

pairs(res[, -1:-2])
```

```{r kmeans}
res2_wide <- res2 %>% 
  spread(issue, b_ebayes)

set.seed(1839)
clust <- kmeans(res2_wide[, -1], 3)

res2_wide$cluster <- factor(clust$cluster)

res2_wide %>% 
  select(-id) %>% 
  group_by(cluster) %>% 
  summarise_all(mean) %>% 
  gather("issue", "mean", -cluster) %>% 
  ggplot(aes(x = cluster, y = mean)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ issue)
```
